import { Note } from './types';

export const MOCK_NOTES: Note[] = [
  {
    id: '1',
    title: 'Comprehensive Lecture Notes',
    courseCode: 'CS101',
    courseName: 'Intro to Computer Science',
    university: 'Graphic Era University',
    professor: 'Dr. John Doe',
    author: 'Siddharth',
    authorAvatarUrl: 'https://picsum.photos/seed/siddharth/100/100',
    rating: 4.8,
    reviews: 124,
    price: 300,
    previewImageUrl: 'https://gehu.ac.in/assets/images/GEHU-Dehradun-1abd6f9c.webp',
    description: 'Complete notes covering all topics from week 1 to the final exam. Includes diagrams and code snippets.',
    uploadDate: '2023-10-15',
  },
  {
    id: '2',
    title: 'Midterm Exam Study Guide',
    courseCode: 'BIO203',
    courseName: 'Human Anatomy',
    university: 'Graphic Era University',
    professor: 'Dr. Jane Smith',
    author: 'Dhruv',
    authorAvatarUrl: 'https://picsum.photos/seed/dhruv/100/100',
    rating: 4.9,
    reviews: 210,
    price: 300,
    previewImageUrl: 'https://gehu.ac.in/assets/images/GEHU-Dehradun-1abd6f9c.webp',
    description: 'A condensed study guide perfect for acing the midterm. Focuses on key concepts and terminology.',
    uploadDate: '2023-10-20',
  },
  {
    id: '3',
    title: 'Full Semester Notes & Summaries',
    courseCode: 'ECON101',
    courseName: 'Principles of Microeconomics',
    university: 'Graphic Era University',
    professor: 'Dr. Emily White',
    author: 'Abhay',
    authorAvatarUrl: 'https://picsum.photos/seed/abhay/100/100',
    rating: 4.7,
    reviews: 88,
    price: 300,
    previewImageUrl: 'https://gehu.ac.in/assets/images/GEHU-Dehradun-1abd6f9c.webp',
    description: 'Every lecture summarized, plus detailed notes. Essential for understanding supply, demand, and market structures.',
    uploadDate: '2023-09-05',
  },
  {
    id: '4',
    title: 'Final Project Code Walkthrough',
    courseCode: 'CS340',
    courseName: 'Machine Learning',
    university: 'Graphic Era University',
    professor: 'Dr. Alan Turing',
    author: 'Dhruv',
    authorAvatarUrl: 'https://picsum.photos/seed/dhruv/100/100',
    rating: 5.0,
    reviews: 56,
    price: 300,
    previewImageUrl: 'https://gehu.ac.in/assets/images/GEHU-Dehradun-1abd6f9c.webp',
    description: 'Line-by-line explanation of a successful final project. Includes Python code and Jupyter notebooks.',
    uploadDate: '2023-11-01',
  },
  {
    id: '5',
    title: 'Lab Reports Collection',
    courseCode: 'CHEM211',
    courseName: 'Organic Chemistry Lab',
    university: 'Graphic Era University',
    professor: 'Dr. Marie Curie',
    author: 'Ayush',
    authorAvatarUrl: 'https://picsum.photos/seed/ayush/100/100',
    rating: 4.6,
    reviews: 72,
    price: 300,
    previewImageUrl: 'https://gehu.ac.in/assets/images/GEHU-Dehradun-1abd6f9c.webp',
    description: 'A complete set of lab reports with methodology, results, and analysis. Great for reference.',
    uploadDate: '2023-10-28',
  },
  {
    id: '6',
    title: 'Historical Timelines & Analysis',
    courseCode: 'HIST300',
    courseName: 'The Roman Empire',
    university: 'Graphic Era University',
    professor: 'Dr. Indiana Jones',
    author: 'Siddharth',
    authorAvatarUrl: 'https://picsum.photos/seed/siddharth/100/100',
    rating: 4.8,
    reviews: 150,
    price: 300,
    previewImageUrl: 'https://gehu.ac.in/assets/images/GEHU-Dehradun-1abd6f9c.webp',
    description: 'Detailed timelines and in-depth analysis of key events and figures in the Roman Empire.',
    uploadDate: '2023-09-18',
  },
];
